version: "3"
services:
  node-app:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/code
    depends_on:
      - db
    restart: always

  react-app:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/code
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 20s
      timeout: 5s
      retries: 5