version: "3"
services:
  node-app:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/code
    links:
      - db

  react-app:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/code

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb